USE [master]
GO

/****** Object:  Database [bugs-extend]    Script Date: 15/9/2020 23:08:30 ******/
CREATE DATABASE [bugs-extend]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bugs-extend', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\bugs-extend.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'bugs-extend_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\bugs-extend_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bugs-extend].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bugs-extend] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bugs-extend] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bugs-extend] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bugs-extend] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bugs-extend] SET ARITHABORT OFF 
GO

ALTER DATABASE [bugs-extend] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bugs-extend] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bugs-extend] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bugs-extend] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bugs-extend] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bugs-extend] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bugs-extend] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bugs-extend] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bugs-extend] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bugs-extend] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bugs-extend] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bugs-extend] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bugs-extend] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bugs-extend] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bugs-extend] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bugs-extend] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bugs-extend] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bugs-extend] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [bugs-extend] SET  MULTI_USER 
GO

ALTER DATABASE [bugs-extend] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bugs-extend] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bugs-extend] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bugs-extend] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [bugs-extend] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [bugs-extend] SET QUERY_STORE = OFF
GO

ALTER DATABASE [bugs-extend] SET  READ_WRITE 
GO

